Tools sloths: fix after review
ThorsAngerVaNeT/rsschool-app pull request #16
Opened 2022-10-09 15:42 UTC by Ogimly

fix after review 
https://github.com/rolling-scopes/rsschool-app/pull/1781

2022-10-09 16:27 UTC, ThorsAngerVaNeT requested changes

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/assets/locales/en.json
> +    "points": "point | points",
а почему через `|`?

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/memory/GameField.vue
> +        <p>{{ gameTime / 1000 }} {{ $t('memory.time') }}</p>
может 1000 в константу?

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/memory/GameField.vue
> +        this.push2Cards(el, i, index);
я бы переименовал в `pushTwoCards`

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/switchers/ThemeSwitcher.vue
> +      :for="`${ThemeStatus}-theme`"
может с маленькой буквы?

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/utils/canvas-utils.ts
> +  const dStep = e.deltaY > 0 ? scalingStepElement : -scalingStepElement;
stepDelta может назвать?

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Catalog.vue
> +        :disabled="!anyChecked"
`anyChecked` может `someChecked` лучше будет? или даже `isSomeChecked`?

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Guess.vue
> +        <p>{{ gameTime / 1000 }} {{ $t('memory.time') }}</p>
magic number

2022-10-09 16:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Guess.vue
> +          <p class="guess-modal__points">{{ Math.round((guesses * 100) / gameCards.length) }} %</p>
magic number

2022-10-09 17:09 UTC, Ogimly commented on tools/sloths/src/views/Catalog.vue
> +        :disabled="!anyChecked"
is это тоже глагол, глаголы нельзя в компьютед

2022-10-09 17:09 UTC, Ogimly commented on tools/sloths/src/utils/canvas-utils.ts
> +  const dStep = e.deltaY > 0 ? scalingStepElement : -scalingStepElement;
кмк менее понятно. шаг чего? дельта чего?

2022-10-09 17:09 UTC, Ogimly commented on tools/sloths/src/components/switchers/ThemeSwitcher.vue
> +      :for="`${ThemeStatus}-theme`"
да, это я пропустила

2022-10-09 17:10 UTC, Ogimly commented on tools/sloths/src/assets/locales/en.json
> +    "points": "point | points",
Это синтаксис vue i18n

2022-10-09 17:11 UTC, Ogimly commented on tools/sloths/src/views/Guess.vue
> +          <p class="guess-modal__points">{{ Math.round((guesses * 100) / gameCards.length) }} %</p>
тут только нейминг меняла)

2022-10-09 17:12 UTC, Ogimly commented on tools/sloths/src/components/memory/GameField.vue
> +        <p>{{ gameTime / 1000 }} {{ $t('memory.time') }}</p>
как назвать?

2022-10-09 17:18 UTC, Ogimly commented on tools/sloths/src/components/memory/GameField.vue
> +        this.push2Cards(el, i, index);
done

2022-10-09 17:19 UTC, Ogimly commented on tools/sloths/src/components/switchers/ThemeSwitcher.vue
> +      :for="`${ThemeStatus}-theme`"
done

2022-10-09 17:19 UTC, Ogimly commented on tools/sloths/src/views/Catalog.vue
> +        :disabled="!anyChecked"
done

2022-10-09 19:13 UTC, Ogimly commented on tools/sloths/src/components/memory/GameField.vue
> +        <p>{{ gameTime / 1000 }} {{ $t('memory.time') }}</p>
done

2022-10-09 19:14 UTC, Ogimly commented on tools/sloths/src/views/Guess.vue
> +        <p>{{ gameTime / 1000 }} {{ $t('memory.time') }}</p>
done

2022-10-11 05:47 UTC, ThorsAngerVaNeT requested changes

2022-10-11 05:47 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Catalog.vue
>        return !!this.checked.filter((el) => el.checked).length;
Тут кстати как раз можно было наверное и метод some использовать :)

2022-10-11 05:50 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/guess/GuessInfo.vue
> +        <span class="result__time">{{ `${res.time / millisecondInSecond} s` }}</span>
`millisecondInSecond` - `s` пропущена

2022-10-11 05:50 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/memory/GameField.vue
> +        <p>{{ gameTime / millisecondInSecond }} {{ $t('memory.time') }}</p>
Тоже самое

2022-10-11 05:50 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/memory/MemoryInfo.vue
> +          <span class="result__time">{{ `${r.time / millisecondInSecond} s` }}</span>
Тоже самое

2022-10-11 05:50 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Guess.vue
> +        <p>{{ gameTime / millisecondInSecond }} {{ $t('memory.time') }}</p>
Тоже самое

2022-10-11 05:50 UTC, ThorsAngerVaNeT commented on tools/sloths/src/utils/canvas-utils.ts
> +  const dStep = e.deltaY > 0 ? scalingStepElement : -scalingStepElement;
stepDelta - дельта шага
как вариант `scaleStepDelta`

2022-10-11 05:51 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Guess.vue
> +          <p class="guess-modal__points">{{ Math.round((guesses * 100) / gameCards.length) }} %</p>
я бы 100 вынес куда-то

2022-10-11 05:52 UTC, WiiJoy approved these changes

2022-10-11 05:59 UTC, Ogimly commented on tools/sloths/src/views/Guess.vue
> +          <p class="guess-modal__points">{{ Math.round((guesses * 100) / gameCards.length) }} %</p>
это пересчет в проценты. смысл делать константу для процентов вообще не вижу

2022-10-11 07:14 UTC, Ogimly commented on tools/sloths/src/utils/canvas-utils.ts
> +  const dStep = e.deltaY > 0 ? scalingStepElement : -scalingStepElement;
done

2022-10-11 07:14 UTC, Ogimly commented on tools/sloths/src/views/Catalog.vue
>        return !!this.checked.filter((el) => el.checked).length;
done

2022-10-11 07:14 UTC, Ogimly commented on tools/sloths/src/components/memory/MemoryInfo.vue
> +          <span class="result__time">{{ `${r.time / millisecondInSecond} s` }}</span>
done

2022-10-11 07:14 UTC, Ogimly commented on tools/sloths/src/views/Guess.vue
> +        <p>{{ gameTime / millisecondInSecond }} {{ $t('memory.time') }}</p>
done

2022-10-11 09:00 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Guess.vue
> +          <p class="guess-modal__points">{{ Math.round((guesses * 100) / gameCards.length) }} %</p>
> это пересчет в проценты. смысл делать константу для процентов вообще не вижу

вот оно что, а я не понял чтото

2022-10-11 09:00 UTC, ThorsAngerVaNeT approved these changes

2022-10-11 12:04 UTC, merged