Tools sloths: fix after review 2
ThorsAngerVaNeT/rsschool-app pull request #17
Opened 2022-10-15 13:17 UTC by WiiJoy

fix after review, second part
https://github.com/rolling-scopes/rsschool-app/pull/1781

2022-10-15 14:23 UTC, Ogimly commented on tools/sloths/src/components/header/HeaderView.vue
> +    },
мб лучше все таки home() и использовать как `v-show="!home"`

2022-10-15 15:12 UTC, WiiJoy commented on tools/sloths/src/components/header/HeaderView.vue
> +    },
done

2022-10-15 17:40 UTC, Ogimly approved these changes

2022-10-17 11:10 UTC, ThorsAngerVaNeT requested changes

2022-10-17 11:10 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/guess/GuessInfo.vue
> +        :key="`${index}_${sortingOptionsALL[indexAll].text}`"
`OptionsALL` - `ALL` прям капсом надо?

2022-10-17 11:10 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/memory/GameField.vue
>        ];
```suggestion
      this.images = Array.from({ length: 12 }, (x, i) => `${MEMORY_GAME_SPRITE}#memory${i + 1}`);
```
Может вот так сделать?

2022-10-17 11:10 UTC, ThorsAngerVaNeT commented on tools/sloths/src/components/memory/MemoryInfo.vue
> +        :key="`${index}_${sortingOptionsALL[indexAll].text}`"
`ALL`?

2022-10-17 11:10 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Memory.vue
> +          :key="level.level"
```suggestion
          v-for="(item, index) in levels"
          :key="item.level"
```
может так?

2022-10-17 11:10 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Memory.vue
> +          :key="level.level"
ну или что-то ещё вместо `item`, а то `level.level` выглядит странно

2022-10-17 11:15 UTC, WiiJoy commented on tools/sloths/README.md
> +RS SLOTHS is a depository of sloths. View all existing stickers, download the necessary ones or chill a bit - why not? Feel a sloth!
<img width="1288" alt="Снимок экрана 2022-10-17 в 14 15 21" src="https://user-images.githubusercontent.com/73646765/196163586-3f682ad6-da92-4906-8d20-995161084745.png">

2022-10-17 11:24 UTC, WiiJoy commented on tools/sloths/src/components/guess/GuessInfo.vue
> +        :key="`${index}_${sortingOptionsALL[indexAll].text}`"
done

2022-10-17 11:24 UTC, WiiJoy commented on tools/sloths/src/components/memory/GameField.vue
>        ];
ok, done

2022-10-17 11:24 UTC, WiiJoy commented on tools/sloths/src/components/memory/MemoryInfo.vue
> +        :key="`${index}_${sortingOptionsALL[indexAll].text}`"
done

2022-10-17 11:24 UTC, WiiJoy commented on tools/sloths/src/views/Memory.vue
> +          :key="level.level"
done

2022-10-17 11:26 UTC, ThorsAngerVaNeT approved these changes

2022-10-17 11:29 UTC, merged