Tools-sloths: add mouse handlers to create memes
ThorsAngerVaNeT/rsschool-app pull request #5
Opened 2022-09-21 21:58 UTC by Ogimly

1. Add drag-n-drop handler for img and text
2. Add wheel handler for scaling img and text

2022-09-23 08:27 UTC, ThorsAngerVaNeT requested changes

2022-09-23 08:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Create.vue
>      updImage(i: number) {
Я бы переименовал в `updateImage`, не очень много смысла в сокращении

2022-09-23 08:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Create.vue
> +    handleMouseMove(e: MouseEvent) {
Есть мысли как `handeMouseMove` и `handeMouseMoveEl` можно переименовать? Чтобы было более понятно что делают эти методы

2022-09-23 11:15 UTC, Ogimly commented on tools/sloths/src/views/Create.vue
> +    handleMouseMove(e: MouseEvent) {
handeMouseMove именован по аналогии с другими хандлерами - этот на перемещение мышки. 
handeMouseMoveEl - обработчик перемещения мышки на конкретном элементе
Такая же логика именования и в других - handleMouseDown, handleMouseUp и тд

2022-09-23 11:38 UTC, Ogimly commented on tools/sloths/src/views/Create.vue
>      updImage(i: number) {
done

2022-09-23 13:27 UTC, ThorsAngerVaNeT commented on tools/sloths/src/views/Create.vue
> +    handleMouseMove(e: MouseEvent) {
может тогда есть смысл `handeMouseMoveEl` переименовать в `moveElement` или `moveElementByMouse`?

2022-09-23 15:33 UTC, Ogimly commented on tools/sloths/src/views/Create.vue
> +    handleMouseMove(e: MouseEvent) {
done

2022-09-23 16:51 UTC, ThorsAngerVaNeT approved these changes

2022-09-24 08:42 UTC, WiiJoy approved these changes

2022-09-24 12:01 UTC, merged